# Note: toolbarMode is not available in this Streamlit version
# Using CSS and JavaScript approach instead to hide developer buttons

[server]
# Disable CORS for cleaner interface
enableCORS = false

# Disable XSRF protection for development
enableXsrfProtection = false

# Set maximum file upload size to 1MB
maxUploadSize = 1

[browser]
# Disable usage stats gathering
gatherUsageStats = false

[theme]
# Custom dark theme colors
primaryColor = "#4A89F3"
backgroundColor = "#1A1D29"
secondaryBackgroundColor = "#222736"
textColor = "#FFFFFF"